# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\gui\pzh-qrcode.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_generatorType = QtWidgets.QLabel(self.centralwidget)
        self.label_generatorType.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.label_generatorType.setObjectName("label_generatorType")
        self.label_encodeWords = QtWidgets.QLabel(self.centralwidget)
        self.label_encodeWords.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.label_encodeWords.setObjectName("label_encodeWords")
        self.lineEdit_encodeWords = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_encodeWords.setGeometry(QtCore.QRect(90, 40, 301, 20))
        self.lineEdit_encodeWords.setObjectName("lineEdit_encodeWords")
        self.label_showImage = QtWidgets.QLabel(self.centralwidget)
        self.label_showImage.setGeometry(QtCore.QRect(30, 110, 420, 420))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_showImage.setFont(font)
        self.label_showImage.setAutoFillBackground(True)
        self.label_showImage.setStyleSheet("")
        self.label_showImage.setObjectName("label_showImage")
        self.label_symbolVersion = QtWidgets.QLabel(self.centralwidget)
        self.label_symbolVersion.setGeometry(QtCore.QRect(180, 10, 81, 21))
        self.label_symbolVersion.setObjectName("label_symbolVersion")
        self.comboBox_symbolVersion = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_symbolVersion.setGeometry(QtCore.QRect(260, 10, 69, 22))
        self.comboBox_symbolVersion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_symbolVersion.setObjectName("comboBox_symbolVersion")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_symbolVersion.addItem("")
        self.comboBox_generatorType = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_generatorType.setGeometry(QtCore.QRect(100, 10, 69, 22))
        self.comboBox_generatorType.setObjectName("comboBox_generatorType")
        self.comboBox_generatorType.addItem("")
        self.comboBox_generatorType.addItem("")
        self.label_eccLevel = QtWidgets.QLabel(self.centralwidget)
        self.label_eccLevel.setGeometry(QtCore.QRect(340, 10, 61, 21))
        self.label_eccLevel.setObjectName("label_eccLevel")
        self.comboBox_eccLevel = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_eccLevel.setGeometry(QtCore.QRect(400, 10, 69, 22))
        self.comboBox_eccLevel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_eccLevel.setObjectName("comboBox_eccLevel")
        self.comboBox_eccLevel.addItem("")
        self.comboBox_eccLevel.addItem("")
        self.comboBox_eccLevel.addItem("")
        self.comboBox_eccLevel.addItem("")
        self.label_detectorType = QtWidgets.QLabel(self.centralwidget)
        self.label_detectorType.setGeometry(QtCore.QRect(10, 540, 91, 21))
        self.label_detectorType.setObjectName("label_detectorType")
        self.comboBox_detectorType = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_detectorType.setGeometry(QtCore.QRect(90, 540, 69, 22))
        self.comboBox_detectorType.setObjectName("comboBox_detectorType")
        self.comboBox_detectorType.addItem("")
        self.comboBox_detectorType.addItem("")
        self.pushButton_generate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_generate.setGeometry(QtCore.QRect(400, 40, 69, 22))
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.pushButton_selectDestPicturePath = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selectDestPicturePath.setGeometry(QtCore.QRect(10, 70, 71, 22))
        self.pushButton_selectDestPicturePath.setObjectName("pushButton_selectDestPicturePath")
        self.lineEdit_destPicturePath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_destPicturePath.setGeometry(QtCore.QRect(90, 70, 161, 20))
        self.lineEdit_destPicturePath.setText("")
        self.lineEdit_destPicturePath.setObjectName("lineEdit_destPicturePath")
        self.label_destPictureName = QtWidgets.QLabel(self.centralwidget)
        self.label_destPictureName.setGeometry(QtCore.QRect(260, 70, 51, 21))
        self.label_destPictureName.setObjectName("label_destPictureName")
        self.lineEdit_destPictureName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_destPictureName.setGeometry(QtCore.QRect(310, 70, 101, 20))
        self.lineEdit_destPictureName.setText("")
        self.lineEdit_destPictureName.setObjectName("lineEdit_destPictureName")
        self.comboBox_destPictureType = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_destPictureType.setGeometry(QtCore.QRect(420, 70, 48, 22))
        self.comboBox_destPictureType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_destPictureType.setObjectName("comboBox_destPictureType")
        self.comboBox_destPictureType.addItem("")
        self.comboBox_destPictureType.addItem("")
        self.comboBox_destPictureType.addItem("")
        self.label_decodedWords = QtWidgets.QLabel(self.centralwidget)
        self.label_decodedWords.setGeometry(QtCore.QRect(10, 570, 81, 21))
        self.label_decodedWords.setObjectName("label_decodedWords")
        self.lineEdit_decodedWords = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_decodedWords.setGeometry(QtCore.QRect(90, 570, 301, 20))
        self.lineEdit_decodedWords.setText("")
        self.lineEdit_decodedWords.setObjectName("lineEdit_decodedWords")
        self.pushButton_detect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_detect.setGeometry(QtCore.QRect(400, 570, 69, 22))
        self.pushButton_detect.setObjectName("pushButton_detect")
        self.pushButton_selectSrcPicture = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selectSrcPicture.setGeometry(QtCore.QRect(10, 600, 73, 22))
        self.pushButton_selectSrcPicture.setObjectName("pushButton_selectSrcPicture")
        self.lineEdit_srcPicture = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_srcPicture.setGeometry(QtCore.QRect(90, 600, 371, 20))
        self.lineEdit_srcPicture.setText("")
        self.lineEdit_srcPicture.setObjectName("lineEdit_srcPicture")
        self.label_imageSource = QtWidgets.QLabel(self.centralwidget)
        self.label_imageSource.setGeometry(QtCore.QRect(170, 540, 81, 21))
        self.label_imageSource.setObjectName("label_imageSource")
        self.comboBox_imageSource = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_imageSource.setGeometry(QtCore.QRect(250, 540, 69, 22))
        self.comboBox_imageSource.setObjectName("comboBox_imageSource")
        self.comboBox_imageSource.addItem("")
        self.comboBox_imageSource.addItem("")
        self.checkBox_activateSource = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_activateSource.setGeometry(QtCore.QRect(340, 540, 101, 17))
        self.checkBox_activateSource.setObjectName("checkBox_activateSource")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 477, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_symbolVersion.setCurrentIndex(1)
        self.comboBox_generatorType.setCurrentIndex(0)
        self.comboBox_eccLevel.setCurrentIndex(0)
        self.comboBox_detectorType.setCurrentIndex(0)
        self.comboBox_destPictureType.setCurrentIndex(0)
        self.comboBox_imageSource.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pzh-qrcode"))
        self.label_generatorType.setText(_translate("MainWindow", "Generator Type:"))
        self.label_encodeWords.setText(_translate("MainWindow", "Encode Words:"))
        self.lineEdit_encodeWords.setText(_translate("MainWindow", "https://github.com"))
        self.label_showImage.setText(_translate("MainWindow", "TextLabel"))
        self.label_symbolVersion.setText(_translate("MainWindow", "Symbol Version:"))
        self.comboBox_symbolVersion.setItemText(0, _translate("MainWindow", "Auto"))
        self.comboBox_symbolVersion.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_symbolVersion.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_symbolVersion.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_symbolVersion.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_symbolVersion.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox_symbolVersion.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox_symbolVersion.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox_symbolVersion.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox_symbolVersion.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox_symbolVersion.setItemText(10, _translate("MainWindow", "10"))
        self.comboBox_symbolVersion.setItemText(11, _translate("MainWindow", "11"))
        self.comboBox_symbolVersion.setItemText(12, _translate("MainWindow", "12"))
        self.comboBox_symbolVersion.setItemText(13, _translate("MainWindow", "13"))
        self.comboBox_symbolVersion.setItemText(14, _translate("MainWindow", "14"))
        self.comboBox_symbolVersion.setItemText(15, _translate("MainWindow", "15"))
        self.comboBox_symbolVersion.setItemText(16, _translate("MainWindow", "16"))
        self.comboBox_symbolVersion.setItemText(17, _translate("MainWindow", "17"))
        self.comboBox_symbolVersion.setItemText(18, _translate("MainWindow", "18"))
        self.comboBox_symbolVersion.setItemText(19, _translate("MainWindow", "19"))
        self.comboBox_symbolVersion.setItemText(20, _translate("MainWindow", "20"))
        self.comboBox_symbolVersion.setItemText(21, _translate("MainWindow", "21"))
        self.comboBox_symbolVersion.setItemText(22, _translate("MainWindow", "22"))
        self.comboBox_symbolVersion.setItemText(23, _translate("MainWindow", "23"))
        self.comboBox_symbolVersion.setItemText(24, _translate("MainWindow", "24"))
        self.comboBox_symbolVersion.setItemText(25, _translate("MainWindow", "25"))
        self.comboBox_symbolVersion.setItemText(26, _translate("MainWindow", "26"))
        self.comboBox_symbolVersion.setItemText(27, _translate("MainWindow", "27"))
        self.comboBox_symbolVersion.setItemText(28, _translate("MainWindow", "28"))
        self.comboBox_symbolVersion.setItemText(29, _translate("MainWindow", "29"))
        self.comboBox_symbolVersion.setItemText(30, _translate("MainWindow", "30"))
        self.comboBox_symbolVersion.setItemText(31, _translate("MainWindow", "31"))
        self.comboBox_symbolVersion.setItemText(32, _translate("MainWindow", "32"))
        self.comboBox_symbolVersion.setItemText(33, _translate("MainWindow", "33"))
        self.comboBox_symbolVersion.setItemText(34, _translate("MainWindow", "34"))
        self.comboBox_symbolVersion.setItemText(35, _translate("MainWindow", "35"))
        self.comboBox_symbolVersion.setItemText(36, _translate("MainWindow", "36"))
        self.comboBox_symbolVersion.setItemText(37, _translate("MainWindow", "37"))
        self.comboBox_symbolVersion.setItemText(38, _translate("MainWindow", "38"))
        self.comboBox_symbolVersion.setItemText(39, _translate("MainWindow", "39"))
        self.comboBox_symbolVersion.setItemText(40, _translate("MainWindow", "40"))
        self.comboBox_generatorType.setItemText(0, _translate("MainWindow", "MyQR"))
        self.comboBox_generatorType.setItemText(1, _translate("MainWindow", "pzh"))
        self.label_eccLevel.setText(_translate("MainWindow", "ECC Level:"))
        self.comboBox_eccLevel.setItemText(0, _translate("MainWindow", "L - 7%"))
        self.comboBox_eccLevel.setItemText(1, _translate("MainWindow", "M - 15%"))
        self.comboBox_eccLevel.setItemText(2, _translate("MainWindow", "Q - 25%"))
        self.comboBox_eccLevel.setItemText(3, _translate("MainWindow", "H - 30%"))
        self.label_detectorType.setText(_translate("MainWindow", "Detector Type:"))
        self.comboBox_detectorType.setItemText(0, _translate("MainWindow", "zxing"))
        self.comboBox_detectorType.setItemText(1, _translate("MainWindow", "pzh"))
        self.pushButton_generate.setText(_translate("MainWindow", "Generate"))
        self.pushButton_selectDestPicturePath.setText(_translate("MainWindow", "Select Path"))
        self.label_destPictureName.setText(_translate("MainWindow", "File Name:"))
        self.comboBox_destPictureType.setItemText(0, _translate("MainWindow", ".jpg"))
        self.comboBox_destPictureType.setItemText(1, _translate("MainWindow", ".png"))
        self.comboBox_destPictureType.setItemText(2, _translate("MainWindow", ".bmp"))
        self.label_decodedWords.setText(_translate("MainWindow", "Decoded Words:"))
        self.pushButton_detect.setText(_translate("MainWindow", "Detect"))
        self.pushButton_selectSrcPicture.setText(_translate("MainWindow", "Select Picture"))
        self.label_imageSource.setText(_translate("MainWindow", "Image Source:"))
        self.comboBox_imageSource.setItemText(0, _translate("MainWindow", "Camera"))
        self.comboBox_imageSource.setItemText(1, _translate("MainWindow", "Picture"))
        self.checkBox_activateSource.setText(_translate("MainWindow", "Activate Source"))

